# ATTENZIONE: Questo file e' da eseguire solamente dopo che si applica una migrazione al DB e si resettano i dati per riempire nuovamente le tabelle

### ===== Farming Companies =====

###
POST https://localhost:7058/api/v1/farmingCompanies
Content-Type: application/json
// potrebbe essere necessario ri-aggiungere il campo waterSupply

{
  "name": "Colle Spadaro di Vivenzio Antonio",
  "city": "Napoli",
  "address" : "Via Vicinale Spadari 13"
}

### ===== Water Companies =====

###
POST https://localhost:7058/api/v1/waterCompanies
Content-Type: application/json

{
  "name": "ABC Napoli",
  "city": "Napoli",
  "address" : "Via Argine 929",
  "waterSupply" : 10000
}

###
POST https://localhost:7058/api/v1/waterCompanies
Content-Type: application/json

{
"name": "MM Spa",
"city": "Milano",
"address" : "Via del Vecchio Politecnico 8",
"waterSupply" : 12000
}

###
POST https://localhost:7058/api/v1/waterCompanies
Content-Type: application/json

{
  "name": "Acea Spa",
  "city": "Roma",
  "address" : "Piazzale Ostinense 2",
  "waterSupply" : 15000
}

###
POST https://localhost:7058/api/v1/waterCompanies
Content-Type: application/json

{
"name": "Iren Acqua Spa",
"city": "Genova",
"address" : "Via SS. Giacomo e Filippo 7",
"waterSupply" : 10000
}

### ===== Crops =====

###
POST https://localhost:7058/api/v1/farmingCompanies/1/crops
Content-Type: application/json

{
  "tag" : "grano",
  "surfaceArea" : 200,
  "irrigationType" : "Traditional",
  "waterNeeds" : 300,
  "idealHumidity" : 65
}

### ===== Actuators =====

###
POST https://localhost:7058/api/v1/farmingCompanies/1/crops/1/actuators
Content-Type: application/json

{
  "actuatorType" : "Sprinkler",
  "tag" : "irrigatore nord"
}

### ===== Sensors =====

###
POST https://localhost:7058/api/v1/farmingCompanies/1/crops/1/sensors
Content-Type: application/json

{
  "sensorType" : "Temperature",
  "tag" : "sensore di temperatura nord"
}

###
POST https://localhost:7058/api/v1/farmingCompanies/1/crops/1/sensors
Content-Type: application/json

{
  "sensorType" : "Humidity",
  "tag" : "sensore di umidita' est"
}

### ===== ActuatorCommands =====

###
POST https://localhost:7058/api/v1/farmingCompanies/1/crops/1/actuators/1/actuatorCommands
Content-Type: application/json

{
  "state" : "active"
}

###
POST https://localhost:7058/api/v1/farmingCompanies/1/crops/1/actuators/1/actuatorCommands
Content-Type: application/json

{
  "state" : "inactive"
}

###
POST https://localhost:7058/api/v1/farmingCompanies/1/crops/1/actuators/1/actuatorCommands
Content-Type: application/json

{
  "state" : "active"
}

### ===== Measurements =====

###
POST https://localhost:7058/api/v1/farmingCompanies/1/crops/1/sensors/1/measurements
Content-Type: application/json

{
  "measuringUnit" : "C°",
  "value" : 30
}
